/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.vetorswing;

import java.util.Arrays;
import javax.swing.DefaultListModel;

/**
 *
 * @author arthu_uhkw4r8
 */
public class TelaVetor extends javax.swing.JFrame {
    int vet[] = new int[10];
    int ind = 0;
    DefaultListModel lista = new DefaultListModel();
    /**
     * Creates new form TelaVetor
     */
    public TelaVetor() {
        initComponents();
        for(int c=0; c < vet.length; c++){ 
                lista.addElement(vet[c]);
        }
    }

    /**     
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane2 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        spinVet = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        listVet = new javax.swing.JList<>();
        btnRemov = new javax.swing.JButton();
        btnOrd = new javax.swing.JButton();
        btnAd = new javax.swing.JButton();
        lbl_Indice = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(925, 534));
        setMinimumSize(new java.awt.Dimension(925, 534));
        setPreferredSize(new java.awt.Dimension(925, 534));
        setResizable(false);
        setSize(new java.awt.Dimension(925, 534));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        spinVet.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(spinVet);
        spinVet.setBounds(200, 130, 80, 30);

        listVet.setBackground(new java.awt.Color(0, 0, 0));
        listVet.setForeground(new java.awt.Color(204, 204, 204));
        listVet.setModel(lista);
        listVet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listVetMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listVet);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(580, 130, 140, 310);

        btnRemov.setText("Remover");
        btnRemov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemovActionPerformed(evt);
            }
        });
        jPanel1.add(btnRemov);
        btnRemov.setBounds(400, 230, 90, 23);

        btnOrd.setText("Ordenar");
        btnOrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdActionPerformed(evt);
            }
        });
        jPanel1.add(btnOrd);
        btnOrd.setBounds(400, 270, 90, 23);

        btnAd.setText("Adicionar");
        btnAd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdActionPerformed(evt);
            }
        });
        jPanel1.add(btnAd);
        btnAd.setBounds(400, 190, 90, 23);

        lbl_Indice.setForeground(new java.awt.Color(204, 204, 204));
        lbl_Indice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_Indice.setText("[0]");
        jPanel1.add(lbl_Indice);
        lbl_Indice.setBounds(680, 90, 14, 16);

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Vetor");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(580, 90, 28, 16);

        jButton1.setText("Remover Tudo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(390, 320, 120, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\Arquivos\\Arthur\\downloads\\Wallpapers\\vecteezy_front-view-dark-silhouette-of-a-modern-sport-black-car_23977559.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-5, -3, 940, 530);

        jLayeredPane2.add(jPanel1);
        jPanel1.setBounds(0, 0, 930, 530);

        getContentPane().add(jLayeredPane2);
        jLayeredPane2.setBounds(-2, 2, 930, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdActionPerformed
        // TODO add your handling code here:
        Arrays.sort(vet);
        lista.removeAllElements();
         for(int c=0; c < vet.length; c++){ 
                lista.addElement(vet[c]);
        }
    }//GEN-LAST:event_btnOrdActionPerformed

    private void btnAdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdActionPerformed
        // TODO add your handling code here:
        vet[ind] = Integer.parseInt(spinVet.getValue().toString());
        lista.removeAllElements();
        for(int c=0; c < vet.length; c++){ 
                lista.addElement(vet[c]);
        }    
    }//GEN-LAST:event_btnAdActionPerformed

    private void listVetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listVetMouseClicked
        // TODO add your handling code here:
        ind = listVet.getSelectedIndex();
        lbl_Indice.setText("[" + ind + "]");
    }//GEN-LAST:event_listVetMouseClicked

    private void btnRemovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemovActionPerformed
        // TODO add your handling code here:
        vet[ind] = 0;
        lista.removeAllElements();
         for(int c=0; c < vet.length; c++){ 
                lista.addElement(vet[c]);
        }
    }//GEN-LAST:event_btnRemovActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Arrays.fill(vet, 0);
        ind = 0;
        lbl_Indice.setText("[" + ind + "]");
        lista.removeAllElements();
         for(int c=0; c < vet.length; c++){ 
                lista.addElement(vet[c]);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVetor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAd;
    private javax.swing.JButton btnOrd;
    private javax.swing.JButton btnRemov;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Indice;
    private javax.swing.JList<String> listVet;
    private javax.swing.JSpinner spinVet;
    // End of variables declaration//GEN-END:variables
}
